#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 24 20:58:36 2017

@author: Robert
"""

import csv
tickets = {}
f = open("311_Service_Requests_from_2010_to_Present.csv")
reader = csv.DictReader(f)
for row in reader:
    state = row["Complaint Type"]
    tickets[state] = tickets.get(state, 0) + 1
f.close()
worst = sorted(tickets, key = tickets.__getitem__, reverse=True)
for i in range(10):
    print("state", worst[i], "has", tickets[worst[i]], "tickets.")
